# Generated by Django 5.0.6 on 2024-07-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preaching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gospelsong',
            name='status',
        ),
        migrations.AddField(
            model_name='gospelsong',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
