# Generated by Django 5.0.6 on 2024-07-08 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preaching', '0004_quiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preacher',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PreachingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('session_time', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=7)),
                ('scheduled_date', models.DateTimeField()),
                ('is_live', models.BooleanField(default=True)),
                ('preacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preaching.preacher')),
            ],
        ),
    ]
