# Generated by Django 5.0.6 on 2024-07-08 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preaching', '0005_preacher_user_preachingsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='preachingsession',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='preachingsession',
            name='preacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preachingsession',
            name='scheduled_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='preachingsession',
            name='session_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='preachingsession',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
