# Generated by Django 5.0.6 on 2024-07-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preaching', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preachingsession',
            name='session_time',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('preacher', 'Preacher'), ('artist', 'Artist')], max_length=10),
        ),
    ]
