# Generated by Django 5.0.6 on 2024-07-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preaching', '0010_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='gospelsong',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
