# Generated by Django 5.0.6 on 2024-07-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preaching', '0011_gospelsong_download_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('preacher', 'Preacher'), ('artist', 'Artist'), ('admin', 'Admin')], max_length=10),
        ),
    ]
