# Generated by Django 5.0.6 on 2024-07-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preaching', '0012_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='gospelsong',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
