# Generated by Django 5.0.6 on 2024-07-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preaching', '0014_preachingsession_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
